// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeveloperWorkspace = { bound: boolean, workspace_id: string | null, display_name: string | null, root_path: string | null, enabled: boolean, };
