// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeveloperSnooze = { enabled: boolean, until_ms: bigint | null, reason: string | null, };
