// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IanState } from "./IanState";
import type { MotionProfile } from "./MotionProfile";
import type { MovementSpeed } from "./MovementSpeed";
import type { PlayfulState } from "./PlayfulState";

export type IanAction = { "type": "animation.play", name: string, looped: boolean, } | { "type": "movement.move_to", x: number, y: number, speed: MovementSpeed, profile: MotionProfile, } | { "type": "speech.show", text: string, mood: string | null, duration_ms: bigint | null, } | { "type": "bubble.open" } | { "type": "bubble.close" } | { "type": "behavior.run_around", duration_ms: bigint, } | { "type": "behavior.zoomies", duration_ms: bigint, reason: string, } | { "type": "effect.play", name: string, intensity: string, duration_ms: bigint, } | { "type": "appearance.scale_to", scale: number, duration_ms: bigint, } | { "type": "playful.state", state: PlayfulState, until_ms: bigint | null, } | { "type": "playful.diagnostic", timestamp_ms: bigint, reason: string, result: string, cooldown_key: string | null, chosen_reaction_key: string | null, } | { "type": "state.sync", state: IanState, };
