// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IanState } from "./IanState";
import type { MovementSpeed } from "./MovementSpeed";

export type IanAction = { "type": "animation.play", name: string, looped: boolean, } | { "type": "movement.move_to", x: number, y: number, speed: MovementSpeed, } | { "type": "speech.show", text: string, mood: string | null, duration_ms: bigint | null, } | { "type": "bubble.open" } | { "type": "bubble.close" } | { "type": "behavior.run_around", duration_ms: bigint, } | { "type": "state.sync", state: IanState, };
