// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IanEvent = { "type": "app.started" } | { "type": "time.tick", now_ms: bigint, } | { "type": "mouse.click", x: number, y: number, } | { "type": "mouse.double_click", x: number, y: number, } | { "type": "mouse.near", x: number, y: number, } | { "type": "mouse.drag_start", x: number, y: number, } | { "type": "mouse.drag_end", x: number, y: number, } | { "type": "dialogue.user_message", text: string, };
