// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BehaviorMode } from "./BehaviorMode";
import type { CurrentBehavior } from "./CurrentBehavior";
import type { DeveloperSnooze } from "./DeveloperSnooze";
import type { DeveloperWorkspace } from "./DeveloperWorkspace";
import type { PlayfulDiagnostic } from "./PlayfulDiagnostic";
import type { PlayfulEnergy } from "./PlayfulEnergy";
import type { PlayfulState } from "./PlayfulState";
import type { Position } from "./Position";
import type { QuietHours } from "./QuietHours";
import type { ScreenBounds } from "./ScreenBounds";

export type IanState = { active_pet_id: string, current_behavior: CurrentBehavior, current_animation: string, position: Position, active_resource_pack: string, behavior_mode: BehaviorMode, reminders_enabled: boolean, reminder_interval_minutes: number, do_not_disturb: boolean, byom_enabled: boolean, byom_key_configured: boolean, git_metadata_enabled: boolean, build_test_events_enabled: boolean, keyboard_rhythm_enabled: boolean, active_app_presence_enabled: boolean, privacy_onboarding_seen: boolean, find_ian_shortcut_enabled: boolean, find_ian_shortcut: string, home_anchor: Position, screen_bounds: ScreenBounds | null, last_user_interaction_ms: bigint, quiet_hours: QuietHours, movement_intensity: string, bubble_frequency: string, rest_behavior: string, playful_energy: PlayfulEnergy, playful_state: PlayfulState, playful_state_until_ms: bigint | null, playful_snoozed_until_ms: bigint | null, last_playful_diagnostic: PlayfulDiagnostic | null, surface_scale: number, diagnostics_enabled: boolean, day_phase: string, is_dragging: boolean, is_bubble_input_active: boolean, developer_workspace: DeveloperWorkspace, developer_snooze: DeveloperSnooze, active_app_category: string | null, };
