// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BehaviorMode } from "./BehaviorMode";
import type { CurrentBehavior } from "./CurrentBehavior";
import type { Position } from "./Position";

export type IanState = { active_pet_id: string, current_behavior: CurrentBehavior, current_animation: string, position: Position, active_resource_pack: string, behavior_mode: BehaviorMode, };
