// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayfulDiagnostic = { timestamp_ms: bigint, reason: string, result: string, cooldown_key: string | null, chosen_reaction_key: string | null, };
